### ISSUE TITLE
[bug] initial signup successs but also threw error

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/ghost-wrapper#5]
After hitting submit on initial signup (fresh install, using .local) the page hung forever.

Ghost logs showed this.

<img width="1335" alt="Screen Shot 2023-01-10 at 9 15 30 AM" src="https://user-images.githubusercontent.com/9935159/211604562-e732a1f2-716b-40d2-a1a3-26efce93838a.png">

However, the admin user was created. After pafe refresh, I was able to log in with the newly created user.

**Comment by k0gen** [comment]
Confirmed. 👍

Well it actually works if you are patient enough (like verrrry patient) .
<img width="1118" alt="Screenshot 2023-01-11 at 17 15 51" src="https://user-images.githubusercontent.com/3606313/211858503-2e4bc72b-14dc-40ed-bf17-8201cb55ce13.png">

But yes waiting 3+ minutes is not acceptable. Looking ...

**Comment by k0gen** [comment]
Fixed in #10
